### ISSUE TITLE
Types as function pointers?

### ISSUE THREAD

**Issue by AndrasKovacs** [u2zv1wx/neut#1]
This is a question about the representation of types as plain function pointers. I do not understand how this is possible in the presence of open/parameterized types. Consider the following pseudocode: 

    dup := lambda (a : tau) (x : a). pair x x
    f := lambda (a : tau)(x : List a). dup (List a) x

In `dup (List a)`,  `List a` is not a closed type, and its copying/freeing implementation depends on `a`, so a static function can't really implement it, and we need to store `a`  at runtime. What I imagine can work, is to have `tau` as a richer type of runtime type codes, which would include a constructor for parameterized inductive types, and generic copy/free would interpret `a : tau`. Of course, for known types, the generic copy/free can be still partially evaluated and inlined.

There is a somewhat similar project called sixten: https://github.com/ollef/sixten. It also supports dependent types with type-passing polymorphism, but there the representation of a type is simply an integer, which is the flat runtime size of the elements of a type; this allows e.g. passing 64 bit numbers and 128 bit unboxed tuples to the same polymorphic identity function. 

In sixten, there is a restriction which allows `tau = Int` to be feasible, namely that all elements of a type must have uniform flat runtime size. This implies e.g. that constructors of inductive types must be padded to uniform size (as in Rust). In sixten, `List : tau -> tau` just returns the uniform size of a list constructor given the uniform size of the parameter type. In contrast, as I see here in neut, the copying behavior of `List a` is not uniform, because different actions have to be performed for `nil` and for `cons`. 

Background: I worked briefly on runtime type-passing and closure conversion with dependent types: here's an [abstract](https://github.com/AndrasKovacs/misc-stuff/blob/master/MemControl/types2018/abstract-types-2018-cconv.pdf) and a [presentation](https://github.com/AndrasKovacs/misc-stuff/blob/master/MemControl/types2018/AndrasKovacs_presentation.pdf). I note that your closures are pretty similar to my closures and [Ahmed/Bowman's](http://www.ccs.neu.edu/home/amal/papers/closconvcc.pdf).

**Comment by u2zv1wx** [comment]
Thank you for your insightful question! I think I can answer to this question by describing how the `List` part of `List a` is translated.

The short answer to the question is: It is possible since the `F` part of `F a` is translated into a closure that chooses an appropriate static function pointer at runtime.

Firstly, as for the `List` example, since `List a` is translated into a Π-type internally, they are copied as closure, which is obviously not what you're asking. I think what you're asking can be rephrased as follows (correct me if I have misinterpreted you).

--

Consider the following pseudo-code:
```
dup := lambda (a : tau) (x : a). pair x x

F := lambda (x : i64).
       if x == 3
         then bool
         else i64 -> i64

f := lambda
       (x : i64)
         (v : F x).
           dup (F x) v
```
In the code above, `F x` is not a closed type, and its copying/freeing implementation depends on `x`. Since `F x : tau` is beta-equivalent to a static function pointer, how can that static pointer can be used to copy `v`?

--

We can, however, obtain the actual type of `v` at runtime by evaluating the function application `F x`. The point would be the fact that the `F`-part is also an ordinary lambda-abstraction that is executed at runtime. The function application `F x` is executed at runtime with argument `x`, choosing a correct function pointer. Does this answer your question?

**Comment by ollef** [comment]
This sounds like the same approach that Sixten uses to compile parameterised types, it's just that we use different type representations.

I think what Andras was wondering was if you're able to use a different runtime representation (e.g. size) for the different constructors of an inductive type like `List`, and if so how? :)

About the uniformity situation in Sixten: it was improved about a year ago, when I added support for [`boxed` types](https://github.com/ollef/sixten#boxed-types), which don't pad the constructors to be uniform. You'd typically use that for types like `List`.

**Comment by AndrasKovacs** [comment]
> since List a is translated into a Π-type internally

I assume this means that inductive types are impredicative Church-encodings? Now I see in the readme that the `list.case` example is not dependently typed, which matches that we don't have dependent elimination with Church-encodings. I see that existential types are also Church-encoded.

I think I understand how this works: the only open type in `neut` is the dependent function type, and for that the copy/free implementation does not actually depend on the domain and codomain types, as only the type of the captured environment is relevant, which is stored internally in closures. So, from the perspective of copy/free, there aren't any open types, and the plain function representation is possible. Is this correct? In any case, thanks for the explanation.

However, would you agree that "native" inductive types (with dependent elimination) and full sigma types would require a richer structural runtime type representation? In that case, I don't see a way around the issue described in my previous post here.

**Comment by u2zv1wx** [comment]
> However, would you agree that "native" inductive types (with dependent elimination) and full sigma types would require a richer, structural runtime type representation?

I tried and failed to give an immediate answer. Maybe yes, but I can't provide a clear reason.

> I think I understand how this works: the only open type in neut is the dependent function type, and for that the copy/free implementation does not actually depend on the domain and codomain types, as only the type of the captured environment is relevant, which is stored internally in closures. So, from the perspective of copy/free, there aren't any open types, and the plain function representation is possible. Is this correct? In any case, thanks for the explanation.

Correct. My pleasure.
