### ISSUE TITLE
What is the "rest+" syntax?

### ISSUE THREAD

**Issue by akavel** [u2zv1wx/neut#3]
The readme, as well as some files in neut-core, seem to use a "rest+" or "r+" syntax a few times. Is this a "varargs-like" syntax, or is "+" just allowed in leafs and has no special meaning? If it's varargs-like, could you please write a bit about it in the readme? I'm especially curious if I can use it in `(notation ...)`, such that I could e.g. define a "varargs" constructor for a list with it? Thanks! :)

PS. Please note I don't know nothing about type theory, so I would be super grateful for a reply generously crafted at my level of comprehension, thanks!  ❤️ 🐣

**Comment by u2zv1wx** [comment]
Oh sorry. I forgot to write it in the document. "+" has a special meaning when used in `(notation ...)`.

It means 1 or more times of occurrence of trees. I think it would be easier to understand via an example.

The `list.neut` file in the core library contains the following code:
```
(notation (list.new a)
  (list.cons * a (list.nil *)))

(notation (list.new a rest+)
  (list.cons * a (list.new rest+)))
```
Yes, the "varargs"-like notation. With the definition above, for example, if we write a term `(list.new 1 2 3)`, it is expanded recursively as follows:
```
(list.new 1 2 3)
~> (list.cons * 1 (list.new 2 3))               [here we have `rest+ ~> 2 3`]
~> (list.cons * 1 (list.cons * 2 (list.new 3))) [here we have `rest+ ~> 3`]
~> (list.cons * 1 (list.cons * 2 (list.cons * 3 (list.nil *))))
```
So, we can realize "varargs"-like constructor. I'll have to update the readme.

**Comment by akavel** [comment]
Awesome & super cool, thanks! 😄😄😄 so the constructor is actually already there, nice!
