### ISSUE TITLE
readme: core/1.0.0.0 -> core/0.1.0.0 ?

### ISSUE THREAD

**Issue by akavel** [u2zv1wx/neut#4]
The neut & neut-core readmes seem to contain a lot of code fragments like below:

```
(ensure core/1.0.0.0
  "https://github.com/u2zv1wx/neut-core/raw/master/release/0.1.0.0.tar.gz")

; ...

(include "core/0.1.0.0/core.neut")
```

Shouldn't the `(ensure ...)` directives have `0.1.0.0` instead of `1.0.0.0`, to match what's then used in the `(include ...)` ones?

**Comment by u2zv1wx** [comment]
You're right. Thank you for correction. I've just fixed it.
