### ISSUE TITLE
Reason for existence of `neut archive`?

### ISSUE THREAD

**Issue by L-as** [u2zv1wx/neut#7]
Is there any reason for this, considering the fact that it doesn't differ much creating it yourself, or just downloading it from GitHub as such: https://github.com/u2zv1wx/neut-core/archive/master.tar.gz? It's obviously a bit different, since it adds the name of the repository to the beginning of the paths inside the archive, but it seems vastly simpler than having a custom process for creating tar archives.

**Comment by u2zv1wx** [comment]
The intention of `archive` is to add an abstraction layer.

For example, a tar archive may or may not create the outer directory (the archives generated by GitHub do). Let's suppose that we want to provide a library `foo`. Using the `tar` command, we might by mistake construct an archive that creates the outer directory. In that case, the resulting files of `(ensure foo/0.3.2.8 "${URL}")` are extracted into `foo/0.3.2.8/foo/(...)`, not `foo/0.3.2.8/(...)`. This would cause problems. Therefore, in that case, we would have to show users how to create an archive that doesn't create the outer directory, for example by adding platform-dependent instructions in the readme.

The abstraction layer provided by `archive` / `ensure` is something that absorbs such internal difference. As long as programmers use archives via `archive` / `ensure`, they don't have to care about how those archives are structured (theoretically, they don't even have to know the format of an archive). This is why I chose to add the subcommand `archive`.

This doesn't mean, though, that I stick to the current implementation. I would happily remove this subcommand if I found a convincing argument against the necessity of it – There's not much more pleasant than removing unnecessary code.

**Comment by L-as** [comment]
This is a bit off-topic, but IMO there are multiple problems with the current "module" system.

In a somewhat random order:
- You can override dependencies installed by other files by specifying the same output directory with `ensure` (of course the efficacy of this depends on which gets loaded first)
- There is no checksum checking to make sure that you have the correct dependency, which would also allow getting your libraries from an alternative source, since if the checksum matches, then there's a very high chance of it being the required dependency. In addition, this would prevent errors due to corruption of the local cache of dependencies, e.g. due to user error (accidental rm -rf) or filesystem corruption
- In the case of a diamond-like dependency tree (i.e., A needs B and C, B and C both need D), it is easy to accidentally include the same file twice, since it's probable that each dependency specifies a different output directory with `ensure`
- There is no "namespacing", meaning that different versions of the same library will have the same names, which will cause a conflict. You can trivially test this by just having an `ensure` for the core library twice with different output directories.

I am not sure what the best way to solve all these problems are, but they are IMO blockers for neut becoming widely used, since using dependencies is a pain. You of course don't want a huge dependency tree like e.g. Cargo or NPM, where you need to trust every single dependency, but in the case of a fully pure language (which neut is if you erase all the impurities and make pure abstractions for them), then you don't need to trust them, since you can be sure that dependencies can only do what their type says.

**Comment by L-as** [comment]
I just realized, you can `include` dependencies you haven't `ensure`d.

**Comment by u2zv1wx** [comment]
I would not say that the current implementation of the dependency system is ready for daily use, of course. It is meant to be an initial sketch, and definitely requires sophistication (or total rewriting).

I thank you for making the room of improvement easier to grasp. I'll try to write down my current thoughts on the points that you kindly made:

> There is no checksum checking to make sure that you have the correct dependency, which would also allow getting your libraries from an alternative source, since if the checksum matches, then there's a very high chance of it being the required dependency.

Yes, it is definitely a desired feature (Indeed, the feature is already included in the "someday" section of my private todo list). The naive implementation would be to allow users to specify checksum information in `ensure`. The implementation itself would be not so difficult. I am willing to implement it after taking enough rest.

> There is no "namespacing", meaning that different versions of the same library will have the same names, which will cause a conflict. You can trivially test this by just having an ensure for the core library twice with different output directories.

Yes, this would cause a pain. Thank you for making me aware of this. The naive solution would be to prohibit using multiple versions of a library, but it seems to be too restrictive. I definitely need to look for a better way to handle this.

> You can override dependencies installed by other files by specifying the same output directory with `ensure` (of course the efficacy of this depends on which gets loaded first)

> In the case of a diamond-like dependency tree (i.e., A needs B and C, B and C both need D), it is easy to accidentally include the same file twice, since it's probable that each dependency specifies a different output directory with `ensure`

Correct. At the same time, however, these are intended behavior, with the following intention:

The documentation of a library is expected to contain information on how to `ensure` it. For example, the documentation of the core library suggests users to `ensure` it into `core/0.1.0.0`. As long as users follow the instruction specified in the documentation, a library is downloaded in an integrated way. The current library management system can be considered as something in which the name of a library is specified by its user, not its author.

> you can include dependencies you haven't `ensure`d.

This is intended behavior. Currently I don't have a reason to prohibit this. Once `ensure`d, a file in a project is no different than a file in the ensured library.

**Comment by L-as** [comment]
Off topic, but I really like this project. I hope it becomes popular since it fills a niche that isn't really filled by any other language. Thanks.

> This is intended behavior. Currently I don't have a reason to prohibit this. Once ensured, a file in a project is no different than a file in the ensured library.

I think this is a great idea, but I don't see why this has to mean that you can use files you haven't `ensure`d. Allowing you to use files from projects you don't explicitly depend on can result in other people not being able to compile your project, since they might not have the required libraries in the cache. In addition, removing a dependency from your project would entail manually searching for `include`s of the files since you won't get errors from removing the `ensure`, unless you also remove the entry in the cache.

It's not a huge issue, and there might be other ways to fix them, but I think it's important to declare your dependencies for the sake of reproducibility; it's not uncommon for me to encounter projects that don't specify all their dependencies which is much more noticeable on NixOS, where you have to specify them all explicitly since it's all compiled in a sandbox.

In any case, I don't think much can be done about the above issue without first considering the other points, since they are deeply intertwined, but I don't think solving this problem would be a hard task. A somewhat simple band-aid could be having `ensure` unpack the archive into a folder, where the folder name is hash of the archive. This would mean that users can't choose where to unpack the folder, and the user-specified name would instead specify the location of the virtual "file system" entry, so that effectively nothing in the language would change.

**Comment by u2zv1wx** [comment]
Thank you for suggestions, including the hash-based system. It sounds promising.

Also, now I think that your point on `ensure` (or reproducibility) is completely valid, thanks to your clear explanation. Towards the goal, it seems to me that we can split the current `include` into the one for a library and the other one for a user program. The former one will be something that includes a library file, which must be `ensure`d beforehand. The latter one will be something that corresponds to the current `include` with a relative path. I'll add this to my todo list.

Anyway, I think we are too off-topic now (though it was constructive). Can we close this issue?

**Comment by L-as** [comment]
Yeah, definitely, thanks.
